// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/bytedance/byte/project/learnCode/tech-learning/notes/doc_js/node_modules/.pnpm/dumi@2.2.1_prettier@2.8.8/node_modules/dumi/theme-default/slots/HeroTitle/index.js';
